# GOV.UK Homepage
- contentful_space_id: q15b851vpa2y
  contentful_entry_id: 64EsT2ttgsJMDm6VxnOWtX
  content_id: 31681f08-9e4d-4709-b995-840a695ed54c
  publishing_api_attributes:
    base_path: /homepage-contentful
    title: GOV.UK homepage
    description: ""
    rendering_app: frontend
